#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" --settings_skipverification=true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  only:
    - master

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> setup.cake
